### ISSUE TITLE
Can't install using npm on Kubuntu 15.04

### ISSUE THREAD

**Issue by CODeRUS** [cjb/GitTorrent#11]
```
sudo npm install gittorrent
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.10.25","npm":"1.4.21"})
 
> dtrace-provider@0.4.0 install /home/coderus/node_modules/gittorrent/node_modules/webtorrent/node_modules/chromecast-js/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing dtrace-provider@0.4.0
 
> utf-8-validate@1.1.0 install /home/coderus/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.0.4-040004-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/coderus/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
 
> bufferutil@1.1.0 install /home/coderus/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.0.4-040004-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/coderus/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
-
> wrtc@0.0.55 install /home/coderus/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing wrtc@0.0.55
gittorrent@0.1.5 ../node_modules/gittorrent
├── inherits@2.0.1
├── hat@0.0.3
├── zero-fill@2.2.1
├── ut_gittorrent@0.1.1 (bencode@0.7.0)
├── magnet-uri@4.2.3 (flatten@0.0.1, xtend@4.0.0, thirty-two@0.0.2)
├── elliptic@3.0.3 (brorand@1.0.5, hash.js@1.0.3, bn.js@2.0.5)
├── prettyjson@1.1.2 (colors@0.6.2, minimist@1.1.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── bittorrent-swarm@5.0.2 (speedometer@0.1.4, addr-to-ip-port@1.4.1, debug@2.2.0, dezalgo@1.0.2)
├── ut_metadata@2.7.3 (bitfield@1.1.1, bencode@0.7.0, simple-sha1@2.0.7)
├── bittorrent-dht@3.1.0 (thunky@0.1.0, isarray@0.0.1, buffer-equal@0.0.1, addr-to-ip-port@1.4.1, network-address@1.0.0, simple-get@1.3.3, sha.js@2.4.1, k-bucket@0.4.2, bencode@0.7.0, debug@2.2.0, once@1.3.2, is-ip@1.0.0, run-parallel@1.1.1, string2compact@1.2.2, compact2string@1.4.0)
├── glob@5.0.10 (path-is-absolute@1.0.0, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── webtorrent@0.32.0 (thunky@0.1.0, speedometer@0.1.4, clivas@0.2.0, range-parser@1.0.2, end-of-stream@1.1.0, bitfield@1.1.1, pump@1.0.0, addr-to-ip-port@1.4.1, network-address@1.0.0, simple-get@1.3.3, xtend@4.0.0, random-access-file@0.3.1, re-emitter@1.1.1, run-parallel@1.1.1, multistream@1.5.0, bittorrent-swarm@2.1.0, mime@1.3.4, block-stream@0.0.7, minimist@1.1.1, debug@2.2.0, windows-no-runnable@0.0.6, mkdirp@0.5.1, moment@2.10.3, once@1.3.2, dezalgo@1.0.2, simple-sha1@2.0.7, nodebmc@0.0.5, ut_pex@1.0.3, parse-torrent@4.1.0, rimraf@2.3.4, load-ip-set@1.2.3, inquirer@0.8.5, pretty-bytes@1.0.4, create-torrent@3.11.1, airplay-js@0.2.15, chromecast-js@0.1.7, torrent-discovery@2.3.2)
└── bittorrent-protocol@1.5.8 (speedometer@0.1.4, bitfield@1.1.1, xtend@4.0.0, bencode@0.7.0, debug@2.2.0, zuul@3.0.0)
```

**Comment by cjb** [comment]
@CODeRUS I don't know what's happening there, but reading closely this looks like a warning rather than an error, so I think the install actually worked?

**Comment by CODeRUS** [comment]
It's not working, git saying following: ```fatal: Unable to find remote helper for 'gittorrent'```

**Comment by cjb** [comment]
@CODeRUS How about if you add -g, like:

sudo npm install -g gittorrent

**Comment by CODeRUS** [comment]
output:
```
sudo npm install -g gittorrent
[sudo] password for coderus: 
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.10.25","npm":"1.4.21"})
 
> dtrace-provider@0.4.0 install /usr/local/lib/node_modules/gittorrent/node_modules/webtorrent/node_modules/chromecast-js/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing dtrace-provider@0.4.0
 
> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.0.4-040004-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
 
> bufferutil@1.1.0 install /usr/local/lib/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.0.4-040004-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing bufferutil@1.1.0
 
> wrtc@0.0.55 install /usr/local/lib/node_modules/gittorrent/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                                           
 
npm WARN optional dep failed, continuing wrtc@0.0.55
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
/usr/local/bin/git-remote-gittorrent -> /usr/local/lib/node_modules/gittorrent/git-remote-gittorrent
/usr/local/bin/gittorrentd -> /usr/local/lib/node_modules/gittorrent/gittorrentd
gittorrent@0.1.5 /usr/local/lib/node_modules/gittorrent
├── inherits@2.0.1
├── hat@0.0.3
├── zero-fill@2.2.1
├── ut_gittorrent@0.1.1 (bencode@0.7.0)
├── magnet-uri@4.2.3 (flatten@0.0.1, xtend@4.0.0, thirty-two@0.0.2)
├── prettyjson@1.1.2 (colors@0.6.2, minimist@1.1.0)
├── elliptic@3.0.3 (brorand@1.0.5, hash.js@1.0.3, bn.js@2.0.5)
├── ut_metadata@2.7.3 (bitfield@1.1.1, bencode@0.7.0, simple-sha1@2.0.7)
├── bittorrent-swarm@5.0.2 (speedometer@0.1.4, addr-to-ip-port@1.4.1, dezalgo@1.0.2, debug@2.2.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── bittorrent-dht@3.1.0 (thunky@0.1.0, isarray@0.0.1, buffer-equal@0.0.1, addr-to-ip-port@1.4.1, network-address@1.0.0, simple-get@1.3.3, sha.js@2.4.1, k-bucket@0.4.2, bencode@0.7.0, once@1.3.2, is-ip@1.0.0, run-parallel@1.1.1, string2compact@1.2.2, debug@2.2.0, compact2string@1.4.0)
├── glob@5.0.10 (path-is-absolute@1.0.0, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── webtorrent@0.32.0 (thunky@0.1.0, speedometer@0.1.4, clivas@0.2.0, range-parser@1.0.2, end-of-stream@1.1.0, bitfield@1.1.1, pump@1.0.0, addr-to-ip-port@1.4.1, network-address@1.0.0, simple-get@1.3.3, xtend@4.0.0, random-access-file@0.3.1, re-emitter@1.1.1, run-parallel@1.1.1, multistream@1.5.0, bittorrent-swarm@2.1.0, mime@1.3.4, once@1.3.2, block-stream@0.0.7, minimist@1.1.1, debug@2.2.0, windows-no-runnable@0.0.6, dezalgo@1.0.2, simple-sha1@2.0.7, mkdirp@0.5.1, ut_pex@1.0.3, moment@2.10.3, rimraf@2.3.4, nodebmc@0.0.5, parse-torrent@4.1.0, load-ip-set@1.2.3, pretty-bytes@1.0.4, airplay-js@0.2.15, inquirer@0.8.5, create-torrent@3.11.1, chromecast-js@0.1.7, torrent-discovery@2.3.2)
└── bittorrent-protocol@1.5.8 (speedometer@0.1.4, bitfield@1.1.1, xtend@4.0.0, bencode@0.7.0, debug@2.2.0, zuul@3.0.0)
```

**Comment by cjb** [comment]
And does it work now?  It looks like it placed git-remote-gittorrent in /usr/local/bin.

**Comment by CODeRUS** [comment]
Testing again:
```git clone gittorrent://github.com/MacManus88/sailfish-pr0gramm
Cloning into 'sailfish-pr0gramm'...```and no more output given

**Comment by cjb** [comment]
That's probably fine; it means no-one's seeding that, and I don't have the fallback to getting it over git:// yet.

**Comment by CODeRUS** [comment]
okay then. where to get info about seeding repos?

**Comment by cjb** [comment]
From the README:
```
Or serve your own repos with:

touch somerepo/.git/git-daemon-export-ok
gittorrentd
```

**Comment by CODeRUS** [comment]
should ```gittorrentd``` stay running after execution? For me it exiting without any output.

**Comment by cjb** [comment]
Yeah, should stay running.  Could you paste:

DEBUG=* gittorrentd

**Comment by CODeRUS** [comment]
Same. No output.

**Comment by cjb** [comment]
Maybe your "touch" didn't work.

**Comment by CODeRUS** [comment]
See following:
```
$ ls
branches  COMMIT_EDITMSG  config  description  GIT_COLA_MSG  git-daemon-export-ok  gitk.cache  HEAD  hooks  index  info  logs  modules  objects  ORIG_HEAD  refs
$ DEBUG=* gittorrentd
```

**Comment by cjb** [comment]
Ah, you need to run gittorrentd from the directory above the git repo.

$ ls ./somerepo/.git # should work
$ gittorrentd

**Comment by CODeRUS** [comment]
This way? Still no ouput:
```
 ~/SailfishProjects $ ls mitakuuluu3/.git
branches  COMMIT_EDITMSG  config  description  GIT_COLA_MSG  git-daemon-export-ok  gitk.cache  HEAD  hooks  index  info  logs  modules  objects  ORIG_HEAD  refs
 ~/SailfishProjects $ DEBUG=* gittorrentd
```

**Comment by cjb** [comment]
Huh.  Sorry, running out of ideas..

**Comment by CODeRUS** [comment]
Keep this updated if you figure it out please :)

**Comment by cjb** [comment]
Is it possible that your network blocks outgoing port 6881 connections?

**Comment by CODeRUS** [comment]
Everything is possible. Any way to test it?

**Comment by cjb** [comment]
I'm tempted to say "go somewhere else".  :)

**Comment by CODeRUS** [comment]
Well, testing using http://portquiz.net:6881/ passed

**Comment by dpc** [comment]
Was this solved? I have the same problem (gittorrentd just exits after a while).

**Comment by cjb** [comment]
@dpc I ran out of ideas.. could you paste your full terminal session with "DEBUG=* gittorrentd" in case it brings anything up?

**Comment by dpc** [comment]
@cjb stdout: http://sprunge.us/PJIa stderr: http://sprunge.us/cUKE

**Comment by cjb** [comment]
@dpc Thanks, that's interesting.  Can you add the below console.log line to gittorrentd and let me know what gets output?
```
    var ls = git.ls(repo, function (sha, ref) {
        console.log(repo, sha, ref)
```

**Comment by dpc** [comment]
http://sprunge.us/MEid http://sprunge.us/abHN

**Comment by cjb** [comment]
Thanks.  What platform are you on?

**Comment by dpc** [comment]
Fedora 21, x64

**Comment by dpc** [comment]
This line did not executed, did it?

**Comment by cjb** [comment]
No, it didn't.  I think `git ls-remote mioco` failed.  What happens when you run that manually in a shell?

**Comment by dpc** [comment]
```
[futex:tmp/gittorrent]% git ls-remote mioco
fatal: 'mioco' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

...

**Comment by cjb** [comment]
And is "mioco/" inside that directory?  (Does `ls mioco` work?)

**Comment by dpc** [comment]
I edited previous answer.

```
[futex:gittorrent/mioco] (master!)% cd ..
[futex:tmp/gittorrent]% git ls mioco
[futex:tmp/gittorrent]% cd mioco 
[futex:gittorrent/mioco] (master!)% git ls
.gitignore
.travis.yml
Cargo.toml
LICENSE-MPL2
Makefile
README.md
examples/echo.rs
examples/echoplus.rs
examples/mailbox.rs
src/lib.rs
src/tests.rs
```

**Comment by cjb** [comment]
How about `git ls-remote mioco/.git`?

**Comment by dpc** [comment]
```
[futex:tmp/gittorrent]% git ls-remote mioco/.git
fatal: 'mioco/.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dpc** [comment]
```
[futex:tmp/gittorrent]% git --version
git version 2.1.0
```

**Comment by cjb** [comment]
How about:
```
cd mioco
git ls-remote .
```
?

**Comment by cjb** [comment]
And do you have any theories on why your git repository doesn't appear to be a git repository?  :)

**Comment by dpc** [comment]
```
[futex:tmp/gittorrent]% cd mioco 
[futex:gittorrent/mioco] (master!)% git ls-remote .
cb1d756636b21abfdfea8e50b5828a0dadb2bda1        HEAD
5715f619f1d5fc6a5c7c897a847a04a31898b8a1        refs/heads/32-limit
633217c8dcfd510ef2c633236ab90d66bfbe3288        refs/heads/devel
3f98fc3d0424cf64e42b70d8ed778a13c94d664c        refs/heads/dynamic-dispatch
ffc459a246d02cf112cad2822f3edb530b80686f        refs/heads/gh-pages
a8639cd0bd957280b605dcbae7a1a4a22c1e3326        refs/heads/mailboxes
cb1d756636b21abfdfea8e50b5828a0dadb2bda1        refs/heads/master
c27d4fec784216703c989f0b153bb85d0239cc4f        refs/heads/new-design
4e81bffeacde4259f29b8cfd6eafde2ba1e51ec6        refs/heads/new-design-squash
92a6541869e7a57a6059e0613f6d0c630fa38131        refs/heads/new-select-api
c97d8b13d98bc354282d386cdd427a1cac211cbd        refs/heads/new-select-api2
92a6541869e7a57a6059e0613f6d0c630fa38131        refs/heads/new-select-api3
e06a510a0af27df4e8de4f8be6938989f3d2b98b        refs/heads/notifyr
df6ff78e7fb514783f86dcfe1f6befc126a7aa38        refs/heads/queue
8b127e6f40a2702e348edfe914e036f6e7cd5ade        refs/heads/spin
c97d8b13d98bc354282d386cdd427a1cac211cbd        refs/heads/spinfix
b27e5e99151f5d16e65e0150dc8a2b1956ce08e7        refs/heads/test
c871197b42b9d0becf0d6651eda13aca61602d1d        refs/heads/tests
5dd4bc4b6fec22214d3e6cad8e93261148e2a053        refs/heads/timer
1f7bbe6b59d5aa57351065d00bf3b0969606c43a        refs/heads/wakups
e8cb4bd3e0500fe5be3cc35137de4629bc9673f3        refs/remotes/jeremyjh/devel
0c317e073f539641935dee8dc963c8917ba3b8e6        refs/remotes/jeremyjh/gh-pages
09fa02e5e13cddf216b7d3d01c55d0dbfbbd66ef        refs/remotes/jeremyjh/master
365e8765b92cee191d63d7ca4d49ad9d2b790853        refs/remotes/jeremyjh/notify
43c5f0f7bdb58cf459f5de8e55f1b1a36d082baa        refs/remotes/jeremyjh/notifyr
5dd4bc4b6fec22214d3e6cad8e93261148e2a053        refs/remotes/jeremyjh/timer
633217c8dcfd510ef2c633236ab90d66bfbe3288        refs/remotes/origin/devel
ffc459a246d02cf112cad2822f3edb530b80686f        refs/remotes/origin/gh-pages
cb1d756636b21abfdfea8e50b5828a0dadb2bda1        refs/remotes/origin/master
4e81bffeacde4259f29b8cfd6eafde2ba1e51ec6        refs/remotes/origin/new-design-squash
0418edb63120eafa5ffea700d42420d2793375d1        refs/remotes/origin/test
633217c8dcfd510ef2c633236ab90d66bfbe3288        refs/remotes/sync/devel
cb1d756636b21abfdfea8e50b5828a0dadb2bda1        refs/remotes/sync/master
e80dee56f27702a91d216c3412fc83baf62fba53        refs/tags/release-0.0.2
cdfafd312420d697a2431256ddcfcd3d7438c23d        refs/tags/release-0.0.2^{}
3fe9e26594f86cab89bbdb3700fc956f3cc4b43e        refs/tags/release-0.0.4
c9df0f7bed8c78d3a5979592c70a086d13d1f3f2        refs/tags/release-0.0.4^{}
```

**Comment by cjb** [comment]
Oh!  Well that's weird.

**Comment by dpc** [comment]
Let me strace this thing...

**Comment by dpc** [comment]
I think the reason is that my `~` is under git control. I've moved the directory to /tmp and now it works, and theline you pasted did print stuff.

**Comment by dpc** [comment]
BTW. What's the deal with "Can't publish mutable key: doesn't fit in 950 bytes." now?

**Comment by cjb** [comment]
It's because you have too many branches.  :)  That's issue #52.
