### ISSUE TITLE
Crash in BitTorrent DHT

### ISSUE THREAD

**Issue by pdaian** [cjb/GitTorrent#58]
Long-running gittorrent crashes with the following trace (reproduction steps unknown):

```
hash= 3f0fc224fab0389c20e3e7281fb9ff51a475c533
Received handshake for c08084026e299f855f845430688ef0798b1649ee
calling git pack-objects for c08084026e299f855f845430688ef0798b1649ee
Counting objects: 33, done.
Compressing objects: 100% (31/31), done.
Total 33 (delta 1), reused 0 (delta 0)
Finished writing c08084026e299f855f845430688ef0798b1649ee.pack
Received handshake for c08084026e299f855f845430688ef0798b1649ee
calling git pack-objects for c08084026e299f855f845430688ef0798b1649ee
Counting objects: 33, done.
Compressing objects: 100% (31/31), done.
Total 33 (delta 1), reused 0 (delta 0)
Finished writing c08084026e299f855f845430688ef0798b1649ee.pack
81dfc4f5d974b5f716c000b1615c8f02bec320fc
81dfc4f5d974b5f716c000b1615c8f02bec320fc
Received handshake for c08084026e299f855f845430688ef0798b1649ee
calling git pack-objects for c08084026e299f855f845430688ef0798b1649ee
Counting objects: 33, done.
Compressing objects: 100% (31/31), done.
Total 33 (delta 1), reused 0 (delta 0)
Finished writing c08084026e299f855f845430688ef0798b1649ee.pack
81dfc4f5d974b5f716c000b1615c8f02bec320fc
/usr/lib/node_modules/gittorrent/node_modules/bittorrent-dht/node_modules/k-bucket/index.js:225
    if ((id.length <= bytesDescribedByBitIndex)
           ^
TypeError: Cannot read property 'length' of undefined
    at KBucket.determineBucket (/usr/lib/node_modules/gittorrent/node_modules/bittorrent-dht/node_modules/k-bucket/index.js:225:12)
    at KBucket.get (/usr/lib/node_modules/gittorrent/node_modules/bittorrent-dht/node_modules/k-bucket/index.js:258:18)
    at DHT._onPut (/usr/lib/node_modules/gittorrent/node_modules/bittorrent-dht/client.js:485:27)
    at DHT._onQuery (/usr/lib/node_modules/gittorrent/node_modules/bittorrent-dht/client.js:1051:30)
    at DHT._onData (/usr/lib/node_modules/gittorrent/node_modules/bittorrent-dht/client.js:1035:10)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```

**Comment by cjb** [comment]
Thanks, I've seen this too, I filed it here:

https://github.com/feross/bittorrent-dht/issues/66
